### ISSUE TITLE
Is the reference  paper link correct?

### ISSUE THREAD

**Issue by narutojxl** [sair-lab/ni-slam#6]
Hello professor wang,
I was your fan a long time ago and just followed your sair-lab, thanks for your group open sourced many resources to community.
I notice reference paper is 2023 year, `Non-iterative SLAM for Warehouse Robots Using Ground Textures, Kuan Xu, Zheng Yang, Lihua Xie, Chen Wang`, but the paper link is 2018 paper of `Non-iterative RGB-D-inertial odometry`, is it correct?
I want to see some experiments VS some other papers, such as `Hart K M, Englot B, O'Shea R P, et al. Monocular Simultaneous Localization and Mapping using Ground Textures[J]. arXiv preprint arXiv:2303.05946, 2023.`

Best regards
narutojxl

**Comment by xukuanHIT** [comment]
Hi narutojxl,

Arxiv was processing the uploaded paper yesterday. Now, it has been done, and you can access the correct PDF through the link. The comparison with other methods can be found in the new paper.

Best Regards,
Xu Kuan

**Comment by narutojxl** [comment]
thanks author, followed. Close it now!
